
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: invoice_application_development

test:
  <<: *default
  database: invoice_application_test

production:
  <<: *default
  database: d2902enaeak4op
  username: tlqkgqxejzjvfn
  password: ff63481fda310ecc390d60ebe80469c4bad8bd6864b5a12d0419ff6c61c74931
